---
grafana_version: "latest"
grafana_port: "3000"
grafana_data_volume: "grafana-storage"
grafana_labels:
  traefik.enable: "true"
  traefik.http.routers.grafana.rule: "Host(`grafana.{{ inventory_hostname }}`)"
  traefik.http.routers.grafana.entrypoints: "web"
