---

- name: Arch | Pacman update/upgrade
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Arch | Pacman update/upgrade (AUR)
  command: "yay -Syu --noconfirm --needed"
  register: result
  changed_when: not result.stdout
  become: no
