---
- name: Gentoo | Sync and upgrade portage
  portage:
    package: 'sys-apps/portage'
    sync: yes
    oneshot: yes
  become: yes

- name: Gentoo | Upgrade all packages
  portage:
    package: '@world'
    update: yes
    deep: yes
    newuse: yes
    keepgoing: yes
    jobs: 8
    loadavg: 16
    quietbuild: yes
  become: yes

- name: Gentoo | Depclean
  portage:
    depclean: yes
  become: yes
