{
 "title": "Pimoroni Enviroplus Dashboard",
 "description": "Pimoroni Enviroplus dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Current measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Temperature Gauge",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    { "expr": "temperature", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    { "expr": "humidity", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "format": "pressurehpa",
   "valueName": "current",
   "targets": [
    { "expr": "pressure", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Light",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "format": "lux",
   "valueName": "current",
   "targets": [
    { "expr": "lux", "legendFormat": "{{location}}" }
   ]
  },
  { "title": "Historical measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature", "legendFormat": "temperature_raw_{{location}}" },
    {
     "expr": "avg_over_time(temperature[15m])",
     "legendFormat": "temperature_smooth_{{location}}"
    }
   ]
  },
  {
   "title": "Gas (NH3, Oxidising, Reducing)",
   "type": "graph",
   "description": "NH3 -> Ammonia, \nOxidising -> Nitrogen Dioxide,\nReducing -> Carbon Monoxide",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ohm" }
   ],
   "targets": [
    { "expr": "NH3", "legendFormat": "nh3_{{location}}" },
    { "expr": "oxidising", "legendFormat": "oxidising_{{location}}" },
    { "expr": "reducing", "legendFormat": "reducing_{{location}}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "pressure", "legendFormat": "pressure_{{location}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "humidity", "legendFormat": "humidity_{{location}}" }
   ]
  },
  {
   "title": "Proximity",
   "type": "graph",
   "description": "A value (from zero to a couple of thousand) for the proximity, with larger numbers being closer proximity and vice versa.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "proximity", "legendFormat": "proximity_{{location}}" }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "description": "A value (from zero to a couple of thousand) for the proximity, with larger numbers being closer proximity and vice versa.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    { "expr": "lux", "legendFormat": "lux_{{location}}" }
   ]
  },
  {
   "title": "Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oxidising - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "rate(oxidising_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Reducing - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "rate(reducing_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "NH3 - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "rate(nh3_measurements_bucket{location=~\"[[location]]\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}