{
 "title": "GrowPi",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "plant",
    "label": "Plant",
    "query": {
     "query": "label_values(grow_soil_saturation, plant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Soil Saturation",
   "type": "bargauge",
   "description": "Saturation display similar to Grow Hat screen. ",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grow_soil_saturation", "legendFormat": "{{ plant }}" }
   ]
  },
  {
   "title": "Soil Saturation Change",
   "type": "stat",
   "description": "Over range",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "avg_over_time(grow_soil_saturation[5m])",
     "legendFormat": "{{ plant }}"
    }
   ]
  },
  {
   "title": "Lux",
   "type": "stat",
   "description": "Lux to Lighting Condition\n\nValue Mappings Obtained Here: https://docs.microsoft.com/en-us/windows/win32/sensorsapi/understanding-and-interpreting-lux-values",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(grow_light_lux[5m])"
    }
   ]
  },
  { "title": "Moisture Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Soil Saturation",
   "type": "graph",
   "description": "Saturation levels over time. ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "grow_soil_saturation", "legendFormat": "{{ plant }}" }
   ]
  },
  {
   "title": "Soil Moisture Reading",
   "type": "graph",
   "description": "Pulses per/second (not packets :)",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    { "expr": "grow_soil_moisture", "legendFormat": "{{ plant }}" }
   ]
  },
  {
   "title": "Light (Lux) Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Light",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "lux" } },
     "yaxes": [
      { "format": "lux" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(grow_light_lux[1m])",
       "legendFormat": "Light"
      }
     ]
    }
   ]
  },
  {
   "title": "Wet/Dry Points Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dry Point",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "grow_soil_dry_point", "legendFormat": "{{ plant }}" }
     ]
    },
    {
     "title": "Wet Point",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "grow_soil_wet_point", "legendFormat": "{{ plant }}" }
     ]
    }
   ]
  }
 ]
}