{
 "title": "Host Overview",
 "description": "Fix bugs of dashboard 3085\n查看单台主机的详细信息",
 "tags": [
  "hosts",
  "prometheus",
  "node-exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "\bPlateform:",
    "query": {
     "query": "label_values(node_boot_time_seconds, job)"
    }
   },
   {
    "name": "node",
    "label": "Node:",
    "query": {
     "query": "label_values(node_boot_time_seconds{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port:",
    "query": {
     "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Filesystem Space Usage (Max)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node:$port*\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$node:$port\"}) / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node:$port*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"$job\",instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{job=\"$job\",instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"$job\",instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{job=\"$job\",instance=~\"$node:$port\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"$job\",instance=~\"$node:$port\"}[24h]))"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"$job\",instance=~\"$node:$port\"}[24h]))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{job=\"$job\",instance=~\"$node:$port\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "sum(node_load5{job=\"$job\",instance=~\"$node:$port\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "sum(node_load15{job=\"$job\",instance=~\"$node:$port\"})",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "cpu busy %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\", instance=~\"$node:$port\"}[1m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum by (instance) (node_memory_MemFree_bytes{job=\"$job\",instance=~\"$node:$port\"} + node_memory_Buffers_bytes{job=\"$job\",instance=~\"$node:$port\"} + node_memory_Cached_bytes{job=\"$job\",instance=~\"$node:$port\"})) / (sum by (instance) (node_memory_MemTotal_bytes{job=\"$job\",instance=~\"$node:$port\"})) ) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"$job\",instance=~\"$node:$port\",job=~\"$job\",device=~\"/dev/.*\"} - node_filesystem_avail_bytes{job=\"$job\",instance=~\"$node:$port\",job=~\"$job\",device=~\"/dev/.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{job=\"$job\",instance=~\"$node:$port\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0) * 8",
     "legendFormat": "{{device}} inbound"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"$job\",instance=~\"$node:$port\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[5m]) > 0) * 8",
     "legendFormat": "{{device}} outbound"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"$job\",instance='$node:$port',device!~'^(md\\\\d+$|dm-|sr0)'}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "UDP Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_udp_queues{instance=~\"$node:$port\",ip=\"v4\"}",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Network Transmit Drops per Hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_transmit_drop_total{instance=~\"$node:$port\"}[1h])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Use per Filesystem",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{job=\"$job\",instance=~\"$node:$port\",fstype=~\"xfs|ext4\"} / node_filesystem_size_bytes{job=\"$job\",instance=~\"$node:$port\",fstype=~\"xfs|ext4\"} * 100)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "MHz" }
   ],
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=~\"$node:$port\"} / 1000 / 1000",
     "legendFormat": "{{ cpu }}"
    }
   ]
  }
 ]
}