---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: archlinux
    box: archlinux/archlinux
    memory: 512
    cpus: 1
  - name: debian
    box: debian/jessie64
    memory: 512
    cpus: 1
#   - name: gentoo
#     box: generic/gentoo
#     memory: 512
#     cpus: 1
#   - name: centos7
#     box: centos/7
#     memory: 512
#     cpus: 1
lint:
  name: yamllint
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
  playbooks:
    prepare: prepare.yml
  lint:
    name: ansible-lint
    options:
      x: ["ANSIBLE0004,ANSIBLE0012"]
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
