---

- hosts: workstations
  connection: local

  tasks:

  - name: MISC | Sync misc Linux configs
    copy:
      src: "files/{{ item }}_configs/"
      dest: "~/.config/{{ item }}/"
    with_items:
      - dunst
      - i3
      - i3status
      - terminator
    when: ansible_distribution != 'MacOSX'
    tags:
      - misc

  roles:
    - packages


- hosts: all
  connection: ssh
  become: no

  roles:
    - base_directories
    - tmux
    - vim
    - zsh


- hosts: servers
  connection: ssh
  become: no
  gather_facts: no

  tasks:

  - name: BASH | Copy bashrc
    copy:
      src: "files/bash_configs/bashrc"
      dest: "~/.bashrc"
      mode: 0600
      backup: yes
    tags:
      - misc
