---

- hosts: workstations:personal_servers
  roles:
    - role: packages
      tags: [ 'pkgs' ]

  tasks:

  - name: Get installed packages
    package_facts:
      manager: auto
    check_mode: no
    tags: misc

  - name: MISC | Sync misc Linux configs
    copy:
      src: "files/{{ item }}_configs/"
      dest: "~/.config/{{ item }}/"
    loop:
      - dunst
      - i3
      # - terminator
    when:
      - ansible_distribution != 'MacOSX'
      - gui|bool
    become: no
    tags:
      - misc

  - name: MISC | Sync misc Linux configs (templates)
    template:
      src: "templates/{{ item.name }}_{{ item.config }}.j2"
      dest: "~/.config/{{ item.name }}/{{ item.config }}"
    loop:
      - { name: 'i3status', config: 'config' }
    when: item.name in ansible_facts.packages
    become: no
    tags:
      - misc

  - name: DOTFILES | Sync terminator Linux configs
    copy:
      src: "files/terminator_configs/config"
      dest: "~/.config/terminator/config"
    when:
      - ansible_distribution != 'Ubuntu'
      - ansible_distribution != 'MacOSX'
      - gui|bool
    become: no
    tags:
      - misc

  - name: DOTFILES | Sync terminator Linux configs (Ubuntu)
    copy:
      src: "files/terminator_configs/config.Ubuntu"
      dest: "~/.config/terminator/config"
    when:
      - ansible_distribution == 'Ubuntu'
    become: no
    tags:
      - misc

  - name: MISC | Ensure options in streamlink config
    blockinfile:
      path: ~/.config/streamlink/config
      create: yes
      block: |
        # Player options
        player=mpv
        player-no-close
    when: gui|bool

- hosts: all
  connection: ssh
  become: no

  roles:
    - role: base_directories
      tags: [ 'git', 'venv' ]
    - role: tmux
      tags: [ 'tmux' ]
    - role: vim
      tags: [ 'vim' ]
    - role: zsh
      tags: [ 'zsh' ]

- hosts: servers
  connection: ssh
  become: no
  gather_facts: no

  tasks:

  - name: BASH | Copy bashrc
    copy:
      src: "files/bash_configs/bashrc"
      dest: "~/.bashrc"
      mode: 0600
      backup: yes
    tags:
      - misc
