---
- hosts: personal_workstations:personal_servers
  pre_tasks:
    - name: Stop wireguard client
      systemd:
        name: "wg-quick@{{ wg_client_defroute_int }}.service"
        state: stopped
      become: yes
      when: wg_client_defroute_int is defined
      tags:
        - never
        - housekeeping

  post_tasks:
    - name: Start wireguard client
      systemd:
        name: "wg-quick@{{ wg_client_defroute_int }}.service"
        state: started
      become: yes
      when: wg_client_defroute_int is defined
      tags:
        - never
        - housekeeping

  roles:
    - role: housekeeping
      tags:
        - never
        - housekeeping
    - role: packages
      tags: pkgs
    - role: cloudalchemy.node-exporter
      tags: node_exporter

  tasks:
  - name: Get installed packages
    package_facts:
      manager: auto
    check_mode: no
    tags: misc
    when: ansible_distribution != 'MacOSX'

  - name: MISC | Create config dirs
    file:
      dest: "~/.config/{{ item }}"
      state: directory
      mode: 0755
    loop:
      - i3status
      - terminator
    when:
      - ansible_distribution != 'MacOSX'
      - item in ansible_facts.packages
    become: no
    tags:
      - misc

  - name: MISC | Sync misc Linux configs
    copy:
      src: "files/{{ item }}_configs/"
      dest: "~/.config/{{ item }}/"
    loop:
      - dunst
      - i3
    when:
      - ansible_distribution != 'MacOSX'
      - gui|bool
    become: no
    tags:
      - misc

  - name: MISC | Sync misc Linux configs (templates)
    template:
      src: "templates/{{ item.name }}_{{ item.config }}.j2"
      dest: "~/.config/{{ item.name }}/{{ item.config }}"
    loop:
      - name: 'i3status'
        config: 'config'
    when:
      - ansible_distribution != 'MacOSX'
      - item.name in ansible_facts.packages
    become: no
    tags:
      - misc

  - name: DOTFILES | Template terminator Linux config
    template:
      src: "templates/terminator_config.j2"
      dest: "~/.config/terminator/config"
    when:
      - ansible_distribution != 'MacOSX'
      - gui|bool
    become: no
    tags:
      - misc

  - name: MISC | Ensure options in streamlink config
    blockinfile:
      path: ~/.config/streamlink/config
      create: yes
      block: |
        # Player options
        player=mpv
        player-no-close
    when: gui|bool

- hosts: all
  connection: ssh
  become: no

  roles:
    - role: base_directories
      tags: [ 'git', 'venv' ]
    - role: tmux
      tags: [ 'tmux' ]
    - role: vim
      tags: [ 'vim' ]
    - role: zsh
      tags: [ 'zsh' ]

- hosts: servers
  connection: ssh
  become: no
  gather_facts: no

  tasks:

  - name: BASH | Copy bashrc
    copy:
      src: "files/bash_configs/bashrc"
      dest: "~/.bashrc"
      mode: 0600
      backup: yes
    tags:
      - misc

- hosts: prometheus
  become: no
  gather_facts: no
  roles:
    - role: prometheus
      tags:
        - docker
        - prometheus

- hosts: grafana
  become: no
  gather_facts: no
  roles:
    - role: grafana
      tags:
        - docker
        - grafana

- hosts: traefik
  become: no
  gather_facts: no
  roles:
    - role: traefik
      tags:
        - docker
        - traefik

- hosts: pihole
  become: no
  gather_facts: no
  roles:
    - role: pihole
      tags:
        - docker
        - pihole