---

- hosts: all
  connection: ssh
  become: no

  tasks:

  # TMUX 
  - name: TMUX | Register tmux version
    command: bash -c "tmux -V | grep -o '.\..'"
    register: tmux_version
    changed_when: False
    check_mode: no
    tags:
      - tmux

  - name: TMUX | Git clone TPM
    git:
      repo: "https://github.com/zeroshift/tpm"
      dest: "~/.tmux/plugins/tpm"
      recursive: yes
      update: yes
    tags:
      - tmux

  - name: TMUX | Create tmux.conf
    template:
      src: templates/tmux/tmux.conf.jinja2
      dest: ~/.tmux.conf
      mode: 0600
      backup: yes
    tags:
      - tmux

  - name: TMUX | Make ~/.tmuxinator
    file:
      path: ~/.tmuxinator
      state: directory
      mode: 0700
    tags:
      - tmux

  # VIM
  - name: VIM | Copy vimrc
    copy:
      src: files/vim_configs/vimrc
      dest: ~/.vimrc
      mode: 0600
      backup: yes
    tags:
      - vim

  - name: VIM | Sync Vim configs
    synchronize:
      src: files/vim_configs/vim/
      dest: ~/.vim/
      #archive: no
      #links: yes
      #perms: yes
      #recursive: yes
      #times: no
      #checksum: yes
    tags:
      - vim

  - name: VIM | Git clone vim plugins
    git:
      repo: "https://github.com/zeroshift/{{ item }}.git"
      dest: "~/.vim/bundle/{{ item }}"
      recursive: yes
      update: yes
    with_items:
      - syntastic
      - tabular
      - vim-flake8
      - vim-fugitive
      - vim-gitgutter
      - vim-puppet
    tags:
      - vim

  # ZSH 
  - name: ZSH | git clone zprezto
    git:
      repo: "https://github.com/zeroshift/prezto.git"
      dest: "~/.zprezto"
      recursive: yes
      update: yes
    tags:
      - zsh

  - name: ZSH | Link rc files
    file:
      src: "~/.zprezto/runcoms/{{ item }}"
      dest: "~/.{{ item }}"
      state: link
    with_items:
      - zlogin
      - zlogout
      - zpreztorc
      - zprofile
      - zshenv
      - zshrc
    tags:
      - zsh


- hosts: workstations
  connection: local

  tasks:
  - name: MISC | Sync misc Linux configs
    synchronize:
      src: "files/{{ item }}_configs/"
      dest: "~/.config/{{ item }}/"
    with_items:
      - dunst
      - i3
      - i3status
      - terminator
    when: ansible_distribution != 'MacOSX'
    tags:
      - misc

  # Software Install
  - name: Install packages | MacOSX
    action: package name={{ item }} state=present
    with_items:
      - htop-osx
      - ipython
      - tmux
      - vim
      - zsh
    become: no
    when: ansible_distribution == 'MacOSX'
    tags:
      - pkgs

  - name: Install packages | Linux default
    action: package name={{ item }} state=present
    become: yes
    with_items:
      - borg
      - chrony
      - cifs-utils
      - dunst
      - feh
      - htop
      - httpie
      - i3lock
      - ipython
      - lsof
      - mutt
      - nfs-utils
      - nmap
      - openssh
      - python-pylint
      - ranger
      - remmina
      - rsync
      - scrot
      - strace
      - sudo
      - terminator
      - tilda
      - tmux
      - vagrant
      - vim
      - virtualbox
      - vlc
      - w3m
      - wget
      - xclip
      - zsh
    when: ansible_distribution != 'MacOSX'
    ignore_errors: true
    tags:
      - pkgs

  - name: Install packages | Gentoo specific
    action: package name={{ item }} state=present
    become: yes
    with_items:
      - app-emulation/virtualbox-modules
      - dev-python/pip
      - dev-python/virtualenv
      - media-fonts/dejavu
      - media-fonts/ubuntu-font-family
      - x11-apps/xhost
    when: ansible_distribution == 'Gentoo'
    tags:
      - pkgs

  - name: Install packages | Arch specific
    action: package name={{ item }} state=present
    become: yes
    with_items:
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-cjk
      - nvidia-settings
      - pkgfile
      - python-pip
      - python-virtualenv
      - util-linux
      - vim-runtime
      - virtualbox-host-dkms
      - wireshark-qt
      - xorg-xhost
    when: ansible_distribution == 'Archlinux'
    tags:
      - pkgs

- hosts: servers
  connection: ssh
  become: no

  tasks:

  - name: BASH | Copy bashrc
    copy:
      src: "files/bash_configs/bashrc"
      dest: "~/.bashrc"
      mode: 0600
      backup: yes
    tags:
      - bash
