---
- hosts: workstations,personal_servers,wsl
  roles:
    - role: packages
      tags: pkgs

  tasks:
    - name: Get installed packages
      package_facts:
        manager: auto
      check_mode: no
      tags: misc
      when: ansible_distribution != 'MacOSX'

    - name: MISC | Create config dirs
      file:
        dest: "~/.config/{{ item }}"
        state: directory
        mode: 0755
      loop:
        - i3status
        - terminator
      when:
        - ansible_distribution != 'MacOSX'
        - item in ansible_facts.packages
      become: no
      tags:
        - misc

    - name: MISC | Sync misc Linux configs
      copy:
        src: "files/{{ item }}_configs/"
        dest: "~/.config/{{ item }}/"
      loop:
        - dunst
        - i3
      when: ansible_distribution != 'MacOSX'
      become: no
      tags:
        - misc

    - name: MISC | Sync misc Linux configs (templates)
      template:
        src: "templates/{{ item.name }}_{{ item.config }}.j2"
        dest: "~/.config/{{ item.name }}/{{ item.config }}"
      loop:
        - name: 'i3status'
          config: 'config'
        - name: 'terminator'
          config: 'config'
      when:
        - ansible_distribution != 'MacOSX'
        - item.name in ansible_facts.packages
      become: no
      tags:
        - misc

- hosts: servers
  connection: ssh
  become: no
  gather_facts: no

  tasks:
    - name: BASH | Copy bashrc
      copy:
        src: "files/bash_configs/bashrc"
        dest: "~/.bashrc"
        mode: 0600
        backup: yes
      tags:
        - misc
