---
- name: Install loki log plugin
  become: true
  command: "docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions"

- name: Deploy docker daemon config
  become: true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
  notify: "Restart docker"
