---
- hosts: personal_workstations:personal_servers
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Stop wireguard client
      systemd:
        name: "wg-quick@{{ wg_client_defroute_int }}.service"
        state: stopped
      when: wg_client_defroute_int is defined
      become: yes

- hosts: personal_servers
  become: yes
  gather_facts: no
  tasks:
    - name: Add default /etc/hosts entries
      lineinfile:
        line: "127.0.0.1 {{ inventory_hostname.split('.') | first }} {{ inventory_hostname }}"
        path: /etc/hosts
        state: present
      tags: etchosts

    - name: Add additional /etc/hosts entries
      lineinfile:
        line: "{{ item }}"
        path: /etc/hosts
        state: present
      loop: "{{ etc_hosts_lines }}"
      when: etc_hosts_lines is defined
      tags: etchosts

- name: Import default playbook
  import_playbook: ../default/playbook-default.yml

# - hosts: personal_workstations:personal_servers
#   gather_facts: no
#   roles:
#     - role: htop
#       tags: htop

- hosts: personal_workstations:personal_servers
  gather_facts: no
  roles:
    - role: cloudalchemy.node_exporter
      tags: node_exporter

- hosts: docker
  become: yes
  gather_facts: no
  roles:
    - role: docker
      tags: docker

- hosts: prometheus
  become: no
  gather_facts: no
  roles:
    - role: prometheus
      tags:
        - docker
        - prometheus

- hosts: homebridge
  become: no
  gather_facts: no
  roles:
    - role: homebridge
      tags:
        - docker
        - homebridge
    - role: homekit_enviroplus
      tags:
        - enviroplus

- hosts: enviroplus_exporter
  become: no
  gather_facts: no
  roles:
    - role: enviroplus_exporter
      tags:
        - enviroplus
        - enviroplus_exporter

- hosts: grow_hat_mini
  become: no
  gather_facts: no
  roles:
    - role: grow_hat_mini
      tags: grow_hat_mini

- hosts: personal_workstations:personal_servers
  become: yes
  gather_facts: no
  tasks:
    - name: Start wireguard client
      systemd:
        name: "wg-quick@{{ wg_client_defroute_int }}.service"
        state: started
      when: wg_client_defroute_int is defined
