---
- hosts: personal_workstations:personal_servers
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Stop wireguard client
      systemd:
        name: "wg-quick@{{ wg_client_defroute_int }}.service"
        state: stopped
      when: wg_client_defroute_int is defined

- hosts: personal_servers
  become: yes
  gather_facts: no
  roles:
    - role: packages
      tags: pkgs

- name: Import default playbook
  import_playbook: ../default/playbook-default.yml

- hosts: personal_workstations:personal_servers
  gather_facts: no
  roles:
    - role: htop
      tags: htop

- hosts: personal_workstations
  become: no
  gather_facts: no
  tasks:
    - name: Ensure options in streamlink config
      blockinfile:
        path: ~/.config/streamlink/config
        create: yes
        block: |
          # Player options
          player=mpv
          player-no-close

- hosts: personal_workstations:personal_servers
  gather_facts: no
  roles:
    - role: cloudalchemy.node-exporter
      tags: node_exporter

- hosts: prometheus
  become: no
  gather_facts: no
  roles:
    - role: prometheus
      tags:
        - docker
        - prometheus

- hosts: grafana
  become: no
  gather_facts: no
  roles:
    - role: grafana
      tags:
        - docker
        - grafana

- hosts: traefik
  become: no
  gather_facts: no
  roles:
    - role: traefik
      tags:
        - docker
        - traefik

- hosts: pihole
  become: no
  gather_facts: no
  roles:
    - role: pihole
      tags:
        - docker
        - pihole

- hosts: homebridge
  become: no
  gather_facts: no
  roles:
    - role: homebridge
      tags:
        - docker
        - homebridge
    - role: homekit_enviroplus
      tags:
        - enviroplus

- hosts: enviroplus_exporter
  become: no
  gather_facts: no
  roles:
    - role: enviroplus_exporter
      tags:
        - enviroplus
        - enviroplus_exporter

- hosts: personal_workstations:personal_servers
  become: yes
  gather_facts: no
  tasks:
    - name: Start wireguard client
      systemd:
        name: "wg-quick@{{ wg_client_defroute_int }}.service"
        state: started
      when: wg_client_defroute_int is defined
