---

- name: GIT | Make "{{ git_repos_path }}" directory
  file:
    path: "{{ git_repos_path }}"
    state: directory
    mode: 0700

- name: VENV | Make "{{ venv_path }}" directory
  file:
    path: "{{ venv_path }}"
    state: directory
    mode: 0700
