---
galaxy_info:
  author: Nick Prendergast
  description: Setup for grow hat mini
  company: N/A
  license: BSD
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 18.04

  galaxy_tags: []
dependencies: []
