---

- name: "Download htop-{{ htop_version }}"
  get_url:
    url: "{{ htop_url }}"
    dest: "/tmp/htop-{{ htop_version }}.tar.gz"
    checksum: "sha256:{{ htop_checksum }}"

- name: "Untar htop-{{ htop_version }}"
  unarchive:
    src: "/tmp/htop-{{ htop_version }}.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/htop-{{ htop_version }}"

- name: Update apt sources
  become: true
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install build dependencies
  become: true
  package:
    name: "{{ htop_deps[ansible_os_family] }}"
    state: present
  vars:
    htop_deps:
      Debian:
        - autoconf
        - build-essential
        - libncurses-dev
      RedHat:
        - autogen
        - automake
        - gcc
        - make
        - ncurses-devel

- name: Build htop
  shell: >-
    ./autogen.sh &&
    ./configure --disable-unicode &&
    make
  args:
    chdir: "/tmp/htop-{{ htop_version }}"
    creates: "/tmp/htop-{{ htop_version }}/htop"

- name: Install htop
  copy:
    src: "/tmp/htop-{{ htop_version }}/htop"
    dest: "{{ htop_install_dir }}/htop"
    mode: 0755
    remote_src: yes
