---
- hosts: k3s_cluster
  gather_facts: no
  become: yes
  tasks:
    - name: Create filesystem for k3s storage
      filesystem:
        fstype: ext4
        dev: /dev/sda1
        force: "{{ k3s_fs_create_force|default(false) }}"
      tags: k3s

    - name: Mount k3s storage
      mount:
        path: /var/lib/rancher
        src: /dev/sda1
        fstype: ext4
        opts: defaults,noatime
        state: present
      tags: k3s

- name: Import k3s playbook
  import_playbook: ../3rd_party/k3s-ansible/site.yml
  tags: k3s

- hosts: master
  gather_facts: no
  pre_tasks:
    - name: Copy remote kubeconfig
      command:
        cmd: "cp /etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/k3s_with_hostname.yaml"
        creates: "/etc/rancher/k3s/k3s_with_hostname.yaml"
      become: yes
      tags:
        - k3s
        - kubeconfig

    - name: Replace hostname
      replace:
        path: "/etc/rancher/k3s/k3s_with_hostname.yaml"
        regexp: "127\\.0\\.0\\.1"
        replace: "{{ groups['master'] | first }}"
      become: yes
      tags:
        - k3s
        - kubeconfig

    # NOTE: If helm is complaining about connecting try "kubectl config view --raw >~/.kube/config.helm && mv ~/.kube/config{.helm,}"
    - name: Write kubeconfig
      fetch:
        src: "/etc/rancher/k3s/k3s_with_hostname.yaml"
        dest: ~/.kube/config
        flat: yes
      become: yes
      tags:
        - k3s
        - kubeconfig

    - name: Set perms on kubeconfig
      file:
        path: ~/.kube/config
        owner: "{{ ansible_user }}"
        mode: 0600
      become: no
      tags:
        - k3s
        - kubeconfig
