---

- name: Clone zprezto
  git:
    repo: "https://github.com/zeroshift/prezto.git"
    dest: "~/.zprezto"
    recursive: yes
    update: yes
  ignore_errors: True
  tags:
    - zsh

- name: Link rc files
  file:
    src: "~/.zprezto/runcoms/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
  tags:
    - zsh
