---

- name: Clone zprezto
  git:
    repo: "https://github.com/zeroshift/prezto.git"
    dest: "~/.zprezto"
    recursive: yes
    update: yes
  ignore_errors: True

- name: Link rc files
  file:
    src: "~/.zprezto/runcoms/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

# - name: chsh on OSX
#   user:
#     name: "{{ ansible_user_id }}"
#     shell: /bin/zsh
#   when: ansible_distribution == "MacOSX"
#   become: yes
