---
galaxy_info:
  author: Nick Prendergast
  description: Install upgrade packages, etc.
  company: N/A
  license: BSD
  min_ansible_version: 2.7

  platforms:
    - name: Archlinux
      versions:
        - all
    - name: Debian
      versions:
        - 10
    - name: Gentoo
      versions:
        - all
    - name: Ubuntu
      versions:
        - 18.04

  galaxy_tags: []
dependencies: []
