---
- name: Include all deployment tasks
  include_tasks:
    file: "{{ deployment }}"
  loop:
    # - loki.yml
    - grafana.yml
    - prometheus.yml
    - alertmanager.yml
    # - consul.yml
    - pihole.yml
  loop_control:
    loop_var: "deployment"
