---
- name: Include all deployment tasks
  include_tasks:
    file: "{{ deployment }}"
  loop:
    # - loki.yml
    - metallb.yml
    # - grafana.yml
    - grafana-helm.yml
    # - prometheus.yml
    - prometheus-helm.yml
    # - alertmanager.yml
    # - pushgateway-helm.yml
    # - consul.yml
    # - pihole.yml
  loop_control:
    loop_var: "deployment"
