---
- name: Include all deployment tasks
  include_tasks:
    file: "{{ deployment }}"
  loop:
    # - loki.yml
    - metallb.yml
    # - grafana.yml
    # - grafana-helm.yml # This is in flux now
    # - prometheus.yml
    # - prometheus-helm.yml  # This is in flux now
    # - alertmanager.yml
    # - pushgateway-helm.yml
    # - consul.yml
    - pihole.yml
  loop_control:
    loop_var: "deployment"
