---
- name: Start nvidia gpu prometheus exporter
  command: >-
    docker run
    --gpus all
    -d
    -p {{ nvidia_gpu_exporter_port }}:9445
    --restart="unless-stopped"
    mindprince/nvidia_gpu_prometheus_exporter:{{ nvidia_gpu_exporter_version }}

- name: Wait for exporter to become ready
  uri:
    url: "http://localhost:{{ nvidia_gpu_exporter_port }}/metrics"
    method: GET
  register: _result
  until: _result.status == 200
  retries: 30
  delay: 2
  when: not ansible_check_mode
