---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: true
  - name: ubuntu
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    pre_build_image: true
  - name: debian
    image: geerlingguy/docker-debian9-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  # config_options:
  #   defaults:
  #     roles_path: ../../../../../default/roles/
verifier:
  name: ansible
