---

- name: Install makepkg dependencies (Arch)
  pacman:
    name: "{{ makepkg_packages }}"
  become: yes
  when: ansible_distribution == 'Archlinux'
  vars:
    makepkg_packages:
      - git
      - binutils
      - fakeroot
      - make
      - gcc

- name: Clone Yay (Arch)
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "~/git/yay"
    update: no
  become: no
  when: ansible_distribution == 'Archlinux'

- name: Install Yay (Arch)
  shell: "set -o pipefail; yes | makepkg -si"
  args:
    executable: /bin/bash
    creates: /usr/sbin/yay
    chdir: "~/git/yay"
  become: no
  when: ansible_distribution == 'Archlinux'

- name: Arch-specific
  pacman:
    name: "{{ arch_packages }}"
    state: present
  become: yes
  vars:
    arch_packages:
      - borg
      - cifs-utils
      - fzf
      - httpie
      - i3-wm
      - mutt
      - nfs-utils
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-cjk
      - nvidia-settings
      - openssh
      - parallel
      - pkgfile
      - python-pip
      - python-pylint
      - python-virtualenv
      - ranger
      - remmina
      - util-linux
      - vim-runtime
      - virtualbox-host-dkms
      - w3m
      - wireshark-qt
      - xclip
      - xorg-xhost
  when: ansible_distribution == 'Archlinux'

- name: Arch-specific (AUR)
  command: "yay -S {{ item }} --noconfirm --needed"
  register: result
  loop:
    - chromedriver
    - google-chrome
    - jre6
    - jre7
    - nocache
    - rundeck-cli
    - tmuxinator
    - vmtouch
  when: ansible_distribution == 'Archlinux'
  changed_when: not result.stdout
  become: no
