---

- name: Debian/Ubuntu-specific
  apt:
    name: "{{ deb_packages }}"
    state: present
  become: yes
  vars:
    deb_packages:
      - ipython3
      - nocache
      - parallel
      - python3-pip
      - python3-virtualenv
      - tmuxinator
      - util-linux
      - vim

- name: Debian/Ubuntu Server/Workstation-specific
  apt:
    name: "{{ deb_packages }}"
    state: present
  become: yes
  vars:
    deb_packages:
      - cifs-utils
      - docker.io
      - nfs-common
      - openssh-client
      - openssh-server
      - nfs-common
  when: >-
    'workstations' in group_names
    or 'personal_servers' in group_names

- name: Debian/Ubuntu-specific (GUI)
  apt:
    name: "{{ deb_packages }}"
    state: present
  become: yes
  vars:
    deb_packages:
      - firefox
      - i3status
      - i3-wm
      - mutt
      - fonts-noto
      - fonts-noto-color-emoji
      - fonts-noto-cjk
      - suckless-tools
      - nvidia-settings
      - remmina
      - terminator
      - w3m
      - wireshark-qt
      - xclip
      - x11-xserver-utils
  when: "'workstations' in group_names"

- name: Ubuntu Workstation-specific
  apt:
    name: "{{ ubu_packages }}"
    state: present
  become: yes
  vars:
    ubu_packages:
      - gnome-tweak-tool
  when:
    - ansible_distribution == "Ubuntu"
    - "'workstations' in group_names"