---

- name: Debian-specific
  apt:
    name: "{{ debian_packages}}"
    state: present
  become: yes
  vars:
    debian_packages:
      - nfs-common
      - openssh-server
      - openssh-client
  ignore_errors: true

- name: Debian-specific
  apt:
    name: "{{ deb_packages }}"
    state: present
  become: yes
  vars:
    deb_packages:
      - borgbackup
      - cifs-utils
      - chromium-chromedriver
      - firefox
      # - fzf
      - httpie
      - i3-wm
      - mutt
      - nfs-common
      - fonts-noto
      - fonts-noto-color-emoji
      - fonts-noto-cjk
      - freerdp-x11
      - google-chrome-stable
      - mattermost-desktop
      - nocache
      - nvidia-settings
      - openssh-client
      - openssh-server
      - parallel
      - python-pip
      - pylint
      - python-virtualenv
      - remmina
      - terminator
      - tmuxinator
      - util-linux
      - vim-runtime
      - virtualbox-dkms
      - vmtouch
      - w3m
      - wireshark-qt
      - xclip
      - x11-xserver-utils
