---

- name: Debian/Ubuntu-specific
  apt:
    name: "{{ deb_packages }}"
    state: present
  become: yes
  vars:
    deb_packages:
      - borgbackup
      - cifs-utils
      # - fzf
      - httpie
      - nfs-common
      - nocache
      - openssh-client
      - openssh-server
      - nfs-common
      - parallel
      - pre-commit
      - python-docker
      - python-pip
      - pylint
      - python-virtualenv
      - ranger
      - tmuxinator
      - util-linux
      - vim-runtime


- name: Debian/Ubuntu-specific (GUI)
  apt:
    name: "{{ deb_packages }}"
    state: present
  become: yes
  vars:
    deb_packages:
      - chromium-chromedriver
      - firefox
      - i3status
      - i3-wm
      - mutt
      - fonts-noto
      - fonts-noto-color-emoji
      - fonts-noto-cjk
      - freerdp-x11
      - google-chrome-stable
      # - slack
      - suckless-tools
      - nvidia-settings
      - remmina
      - terminator
      - vagrant
      - virtualbox
      - virtualbox-dkms
      - w3m
      - wireshark-qt
      - xclip
      - x11-xserver-utils
  when: gui|bool

- name: Ubuntu-specific
  apt:
    name: "{{ ubu_packages }}"
    state: present
  become: yes
  vars:
    ubu_packages:
      - vmtouch
  when: ansible_distribution == "Ubuntu"
