---

- name: Gentoo specific
  package:
    name: "{{ gentoo_packages }}"
    state: present
  become: yes
  vars:
    gentoo_packages:
      - app-backup/borgbackup
      - app-editors/vim
      - app-misc/ranger
      - dev-python/pip
      - dev-python/pylint
      - dev-python/virtualenv
      - media-fonts/liberation-fonts
      - media-fonts/noto
      - media-fonts/source-pro
      - net-analyzer/wireshark
      - net-fs/nfs-utils
      - net-im/slack
      - net-misc/openssh
      - sys-fs/ncdu
      - sys-process/parallel
      - www-client/firefox
      - x11-apps/xhost
      - x11-misc/xclip
      - x11-wm/i3
  when: ansible_distribution == 'Gentoo'
