---

- name: Linux default
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      - chrony
      - git
      - hardlink
      - htop
      - ipython3
      - jq
      - lbzip2
      - lsof
      - nmap
      - pigz
      - rclone
      - rsync
      - strace
      - sudo
      - tcpdump
      - tmux
      - wget
      - zsh
  when: ansible_distribution != 'MacOSX'

- name: Linux default (GUI)
  package:
    name: "{{ gui_packages }}"
    state: present
  become: yes
  vars:
    gui_packages:
      - dunst
      - feh
      - firefox
      - i3lock
      - mpv
      - redshift
      - scrot
      - streamlink
      - terminator
      - tilda
      - vlc
  when:
    - ansible_distribution != 'MacOSX'
    - gui|bool
