---
- name: Linux default
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      - docker-compose
      - git
      - hardlink
      - htop
      - lbzip2
      - lsof
      - pigz
      - rsync
      - strace
      - sudo
      - tmux
      - tree
      - wget
      - zsh
- name: Linux Workstation/Server-default
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      - chrony
      - tcpdump
  when: >-
    'workstations' in group_names
    or 'personal_servers' in group_names

# - name: LinuxBrew Packages
#   ansible.builtin.homebrew:
#     name: "{{ linuxbrew_packages }}"
#     state: present
#   vars:
#     linuxbrew_packages:
#       - "go-jsonnet"
#       - gcc
#       - gh
#       - helm
#       - jsonnet-bundler
#       - kind
#       - kubectl
#       - pyenv
#       - pyenv-virtualenv
#       - yq
#       - jq
#   when:
#     - ansible_distribution != 'MacOSX'
#     - "'workstations' in group_names or 'wsl' in group_names"

- name: Linux default (GUI)
  package:
    name: "{{ gui_packages }}"
    state: present
  become: yes
  vars:
    gui_packages:
      - dunst
      - feh
      - firefox
      - i3lock
      - mpv
      - redshift
      - scrot
      - terminator
      - tilda
      - vlc
  when: "'workstations' in group_names"
