---
- name: Linux default
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      - docker-compose
      - git
      - hardlink
      - htop
      - jq
      - lbzip2
      - lsof
      - nmap
      - pigz
      - rclone
      - rsync
      - strace
      - sudo
      - tmux
      - tree
      - wget
      - zsh
  when: ansible_distribution != 'MacOSX'

- name: Linux Workstation/Server-default
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  vars:
    packages:
      - chrony
      - tcpdump
  when:
    - ansible_distribution != 'MacOSX'
    - "'workstations' in group_names or 'servers' in group_names"

- name: LinuxBrew Packages
  ansible.builtin.homebrew:
    name: "{{ brew_packages }}"
    state: present
    # path: "/home/linuxbrew/.linuxbrew/bin"
  vars:
    brew_packages:
      - "go-jsonnet"
      - gcc
      - gh
      - helm
      - jsonnet-bundler
      - kind
      - kubectl
      - pyenv
      - pyenv-virtualenv
  when:
    - ansible_distribution != 'MacOSX'
    - "'workstations' in group_names or 'wsl' in group_names"

- name: Linux default (GUI)
  package:
    name: "{{ gui_packages }}"
    state: present
  become: yes
  vars:
    gui_packages:
      - dunst
      - feh
      - firefox
      - i3lock
      - mpv
      - redshift
      - scrot
      - streamlink
      - terminator
      - tilda
      - vlc
  when:
    - ansible_distribution != 'MacOSX'
    - "'workstations' in group_names"
