---

- name: Install python2
  homebrew:
    name: python2
    state: present
  become: no
  ignore_errors: true

- name: OSX | Install virtualenv
  pip:
    name: virtualenv
  become: no
  ignore_errors: true

- name: OSX | Install molecule
  pip:
    name: "{{ modules }}"
  become: no
  vars:
    modules:
      - 'molecule[docker]'
      - 'docker'
  ignore_errors: true

- name: OSX | Tap casks
  homebrew_cask:
    name: "{{ casks }}"
    state: present
  vars:
    casks:
      - chromedriver
      - discord
      - docker
      - firefox
      - google-chrome
      - iina
      - iterm2
      - oracle-jdk
      - slack
      - streamlink-twitch-gui
      - vagrant
      - virtualbox
      - virtualbox-extension-pack
  become: no
  ignore_errors: true

- name: MacOSX-specific
  homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - grsync
      - htop-osx
      - hub
      - httpie
      - ipython
      - kubectl
      - mutt
      - nmap
      - ssh-copy-id
      - testdisk
      - tmux
      - vim
      - wget
      - zsh
  become: no
  ignore_errors: true
