---
# - name: OSX | Tap casks
#   homebrew_cask:
#     name: "{{ casks }}"
#     state: present
#   vars:
#     casks:
#       - discord
#       # - docker
#       - firefox
#       - iterm2
#       - wireshark
#   become: no
#   ignore_errors: true

- name: MacOSX-specific
  homebrew:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - grsync
      - htop-osx
      - secretive
      - ssh-copy-id
      - tmux
      - tree
      - vim
      - wget
  become: no
  ignore_errors: true
