---
- include_tasks: Common.yml
  when: >-
    'workstations' in group_names
    or 'wsl' in group_names

- include_tasks: Linux.yml
  when: ansible_distribution != 'MacOSX'

- include_tasks: "{{ ansible_distribution }}.yml"
  when: >-
    ansible_distribution == "MacOSX"
    or ansible_distribution == "Archlinux"
    or ansible_distribution == "Gentoo"

- include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: "Install additional pkgs for {{ ansible_distribution }}"
  package:
    name: "{{ additional_packages[ansible_distribution] }}"
    state: present
  become: yes
  when: "ansible_distribution in additional_packages.keys()"
