---
galaxy_info:
  author: Nick Prendergast
  description: Start all k3s deployments
  company: N/A
  license: BSD
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 20.04

  galaxy_tags: []
dependencies: []
